# Generated by Django 5.0.8 on 2024-08-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quizsessionquestion_answer_quizsession_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz_sessions', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quizsessionchoice',
            name='session_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_choices', to='quiz.quizsessionquestion'),
        ),
        migrations.AlterField(
            model_name='quizsessionquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='quiz.quizsession'),
        ),
    ]
